version: '3.8'
services:
  redis:
    image: redis:7.2-alpine
    container_name: energy-factory-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
